### ISSUE TITLE
CryptoBot library missing

### ISSUE THREAD

**Issue by stabilaprotocol** [yuyasugano/bot#1]
In botter.py line 14 'from cryptobot import CryptoBot'
There is no reference to the used lib.

**Comment by yuyasugano** [comment]
@dantheman1978 Hi Sorry for late. Could you try crypto instead?? There is a crypto.py and CryptoBot class inside.
from crypto import CryptoBot

Please let me know if something is unclear.

**Comment by yuyasugano** [comment]
@dantheman1978 I corrected the code and push it on the main branch, therefore I close the issue. Thanks.
